Vagrant.configure("2") do |config|
  config.vm.box = "hklabbers/Ubuntu-16.04.3-Dev"
  config.vm.box_version = "0.0.2"
  config.vm.hostname = "CPP-DEV"
  config.vm.synced_folder "../workspace", "/workspace"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "C++ Development Box CloudFoundry"
     vb.gui = false
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
     vb.customize ["modifyvm", :id, "--ioapic", "on"]
     vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
     vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.provision :shell, :path => File.join( "BoxSetup", "setup.sh" )

  # Install development dependencies
  config.vm.provision :shell, privileged: false, :path => File.join( "BoxSetup/dev-dependencies", "poco-1.8.1.sh" )
  config.vm.provision :shell, privileged: false, :path => File.join( "BoxSetup/dev-dependencies", "catch2-2.1.1.sh" )
  config.vm.provision :shell, privileged: false, :path => File.join( "BoxSetup/dev-dependencies", "trompeloeil-29.sh" )
  config.vm.provision :shell, privileged: false, :path => File.join( "BoxSetup/dev-dependencies", "curl-7.58.0.sh" )
end
